import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv("netflix_titles.csv")

# clean the data
df = df.dropna(subset=['type', 'release_year', 'duration', 'rating', 'country'])

type_counts = df['type'].value_counts()
plt.figure(figsize=(6, 4))
plt.bar(type_counts.index, type_counts.values, color=['blue', 'orange'])
plt.title('Distribution of Movies and TV Shows on Netflix')
plt.xlabel('Type')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('type_distribution.png')
plt.show()

rating_counts = df['rating'].value_counts()
plt.figure(figsize=(8, 6))
plt.pie(rating_counts.values, labels=rating_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Content Ratings on Netflix')
plt.tight_layout()
plt.savefig('rating_distribution.png')
plt.show()

movie_df = df[df['type'] == 'Movie'].copy()
movie_df['duration'] = movie_df['duration'].str.replace(' min', '').astype(int)

plt.figure(figsize=(8, 6))
plt.hist(movie_df['duration'], bins=30, color='green', edgecolor='black')
plt.title('Distribution of Movie Durations on Netflix')
plt.xlabel('Duration (minutes)')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('movie_duration_distribution.png')
plt.show()

release_year_counts = df['release_year'].value_counts().sort_index()
plt.figure(figsize=(12, 6))
plt.scatter(release_year_counts.index, release_year_counts.values, color='red')
plt.title('Number of Titles Released Each Year on Netflix')
plt.xlabel('Release Year')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('release_year_distribution.png')
plt.show()

country_counts = df['country'].value_counts().head(10)
plt.figure(figsize=(10, 6))
plt.bar(country_counts.index, country_counts.values, color='purple')
plt.title('Top 10 Countries with the Most Titles on Netflix')
plt.xlabel('Country')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('top_countries.png')
plt.show()

director_counts = df['director'].value_counts().head(10)
plt.figure(figsize=(10, 6))
plt.bar(director_counts.index, director_counts.values, color='cyan')
plt.title('Top 10 Directors with the Most Titles on Netflix')
plt.xlabel('Director')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('top_directors.png')
plt.show()